IF NOT EXISTS(SELECT 1 FROM sys.tables WHERE object_id = OBJECT_ID(N'dbo.OpenTabs'))
BEGIN
	CREATE TABLE dbo.OpenTabs
	(
		Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
		[Data] NVARCHAR(MAX) NOT NULL
	)
END
GO