version: '3.4'
services:
  rabbitmq:
    image: ronanmoriarty/rabbitmq-windowsservercore
    ports:
      - "35672:5672"
      - "45672:15672"
  waiter-read-db-server:
    build:
      context: .\src\Cafe\Docker\SqlServer\
      dockerfile: .\ReadModel\Dockerfile
    env_file:
      - .env
    ports:
      - "1401:1433"
  waiter-write-db-server:
    build:
      context: .\src\Cafe\Docker\SqlServer\
      dockerfile: .\WriteModel\Dockerfile
    env_file:
      - .env
    ports:
      - "1400:1433"
  cafe-waiter-event-projecting-service:
    build:
      context: .\src\
      dockerfile: .\Cafe\Cafe.Waiter.EventProjecting.Service\Dockerfile
    depends_on:
      - "rabbitmq"
      - "waiter-read-db-server"
  cafe-waiter-event-projecting-service-tests:
    build:
      context: .\src\
      dockerfile: .\Cafe\Cafe.Waiter.EventProjecting.Service\Dockerfile
      target: test
    volumes:
      - type: bind
        source: .\test-results
        target: C:\test-results
    depends_on:
      - "rabbitmq"
      - "waiter-read-db-server"
  cafe-waiter-command-service:
    build:
      context: .\src\
      dockerfile: .\Cafe\Cafe.Waiter.Command.Service\Dockerfile
    depends_on:
      - "rabbitmq"
      - "waiter-write-db-server"
  cafe-waiter-command-service-tests:
    build:
      context: .\src\
      dockerfile: .\Cafe\Cafe.Waiter.Command.Service\Dockerfile
      target: test
    volumes:
      - type: bind
        source: .\test-results
        target: C:\test-results
    depends_on:
      - "rabbitmq"
      - "waiter-write-db-server"
  cafe-waiter-web:
    build:
      context: .\src\
      dockerfile: .\Cafe\Cafe.Waiter.Web\Dockerfile
    depends_on:
      - "rabbitmq"
      - "waiter-read-db-server"
    ports:
      - "8080:80"
  cafe-waiter-web-tests:
    build:
      context: .\src\
      dockerfile: .\Cafe\Cafe.Waiter.Web\Dockerfile
      target: test
    volumes:
      - type: bind
        source: .\test-results
        target: C:\test-results
    depends_on:
      - "rabbitmq"
      - "waiter-read-db-server"
  cafe-waiter-acceptance-tests:
    build:
      context: .\src\
      dockerfile: .\Cafe\Cafe.Waiter.Acceptance.Tests\Dockerfile
    volumes:
      - type: bind
        source: .\test-results
        target: C:\test-results
      - type: bind
        source: .\chromedriver-logs
        target: C:\chromedriver-logs
    depends_on:
      - "cafe-waiter-event-projecting-service"
      - "cafe-waiter-command-service"
      - "cafe-waiter-web"