version: '3'
services:
  rabbitmq:
    image: ronanmoriarty/rabbitmq-windowsservercore
    ports:
      - "5672"
      - "15672"
  waiter-read-db-server:
    build:
      context: .\src\Cafe\Docker\SqlServer\
      dockerfile: .\ReadModel\Dockerfile
    env_file:
      - .env
    ports:
      - "1401:1433"
  waiter-write-db-server:
    build:
      context: .\src\Cafe\Docker\SqlServer\
      dockerfile: .\WriteModel\Dockerfile
    env_file:
      - .env
    ports:
      - "1400:1433"
  cafe-waiter-event-projecting-service:
    build:
      context: .\src\
      dockerfile: .\Cafe\Cafe.Waiter.EventProjecting.Service\Dockerfile
    depends_on:
      - "rabbitmq"
      - "waiter-read-db-server"
  cafe-waiter-command-service:
    build:
      context: .\src\
      dockerfile: .\Cafe\Cafe.Waiter.Command.Service\Dockerfile
    depends_on:
      - "rabbitmq"
      - "waiter-write-db-server"
  cafe-waiter-web:
    build:
      context: .\src\
      dockerfile: .\Cafe\Cafe.Waiter.Web\Dockerfile
    depends_on:
      - "rabbitmq"
      - "waiter-read-db-server"