version: '3'
services:
  rabbitmq:
    build: .\Docker\RabbitMQ\
  waiter-read-db-server:
    build:
      context: .\Docker\SqlServer\
      dockerfile: .\ReadModel\Dockerfile
    environment:
      - sa_password=${sa_password}
  waiter-write-db-server:
    build:
      context: .\Docker\SqlServer\
      dockerfile: .\WriteModel\Dockerfile
    environment:
      - sa_password=${sa_password}
  cafe-waiter-event-projecting-service:
    build:
      context: .\src\Cafe\
      dockerfile: .\Cafe.Waiter.EventProjecting.Service\Dockerfile
    env_file: .env
    depends_on:
      - "rabbitmq"
      - "waiter-read-db-server"