IF EXISTS(SELECT 1 FROM sys.tables WHERE object_id = OBJECT_ID(N'dbo.OpenTabs'))
BEGIN
	DROP TABLE dbo.OpenTabs
END
GO

CREATE TABLE dbo.OpenTabs
(
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY
	--[Data] NVARCHAR(MAX) NOT NULL,
	--Created DATETIME NOT NULL
)