IF EXISTS(SELECT 1 FROM sys.tables WHERE object_id = OBJECT_ID(N'dbo.TabDetails'))
BEGIN
	DROP TABLE dbo.TabDetails
END
GO

CREATE TABLE dbo.TabDetails
(
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[Data] NVARCHAR(MAX) NOT NULL
)