IF EXISTS(SELECT 1 FROM sys.tables WHERE object_id = OBJECT_ID(N'dbo.Menu'))
BEGIN
	DROP TABLE dbo.Menu
END
GO

CREATE TABLE dbo.Menu
(
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[Data] NVARCHAR(MAX) NOT NULL
)