IF NOT EXISTS(SELECT 1 FROM sys.tables WHERE object_id = OBJECT_ID(N'dbo.EventsToPublish'))
BEGIN
	CREATE TABLE dbo.EventsToPublish
	(
		Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
		EventType NVARCHAR(25) NOT NULL,
		[Data] NVARCHAR(MAX) NOT NULL,
		Created DATETIME NOT NULL
	)
END
GO