IF EXISTS(SELECT 1 FROM sys.tables WHERE object_id = OBJECT_ID(N'dbo.Events'))
BEGIN
	DROP TABLE dbo.Events
END
GO

CREATE TABLE dbo.Events
(
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	EventType NVARCHAR(MAX) NOT NULL,
	[Data] NVARCHAR(MAX) NOT NULL
)